/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...page]': RouteRecordInfo<
      '/[...page]',
      '/:page(.*)',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/arts/': RouteRecordInfo<
      '/arts/',
      '/arts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/arts/[id]': RouteRecordInfo<
      '/arts/[id]',
      '/arts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/collections': RouteRecordInfo<
      '/collections',
      '/collections',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/account-settings': RouteRecordInfo<
      '/dashboard/account-settings',
      '/dashboard/account-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/faqs': RouteRecordInfo<
      '/faqs',
      '/faqs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/js/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'resources/js/pages/[...page].vue': {
      routes:
        | '/[...page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'resources/js/pages/arts/index.vue': {
      routes:
        | '/arts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'resources/js/pages/arts/[id].vue': {
      routes:
        | '/arts/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'resources/js/pages/collections.vue': {
      routes:
        | '/collections'
      views:
        | never
      pathParamNames:
        | never
    }
    'resources/js/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'resources/js/pages/dashboard/account-settings.vue': {
      routes:
        | '/dashboard/account-settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'resources/js/pages/faqs.vue': {
      routes:
        | '/faqs'
      views:
        | never
      pathParamNames:
        | never
    }
    'resources/js/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
